#!/usr/bin/env bash

git config --global core.autocrlf false
git config --global core.eol lf
git config --global core.pager "less -x4"

git config --global alias.a "add"
git config --global alias.aa "add --all"
git config --global alias.ap "add --patch"
git config --global alias.alias "config --get-regexp ^alias\."
git config --global alias.ca "commit --amend"
git config --global alias.cam "commit --amend -m"
git config --global alias.can "commit --amend --no-edit"
git config --global alias.cb "checkout -b"
git config --global alias.cn "commit --no-edit"
git config --global alias.cm "commit -m"
git config --global alias.d "diff --ignore-all-space"
git config --global alias.dh "diff --ignore-all-space HEAD"
git config --global alias.di "diff --ignore-all-space --cached"
git config --global alias.dw "diff --ignore-all-space --"
git config --global alias.fp "fetch --all --prune"
git config --global alias.ld "log --graph --date=short --pretty=format:'%C(yellow)%h%C(cyan) %ad%C(red)%d%Creset %s  %C(green)%an%Creset' --abbrev-commit --stat --summary"
git config --global alias.ls "log --graph --date=short --pretty=format:'%C(yellow)%h%C(cyan) %ad%C(red)%d%Creset %s  %C(green)%an%Creset' --abbrev-commit"
git config --global alias.la "log --graph --date=short --pretty=format:'%C(yellow)%h%C(cyan) %ad%C(red)%d%Creset %s  %C(green)%an%Creset' --abbrev-commit --branches --remotes --tags"
git config --global alias.lsa "log --graph --date=short --pretty=format:'%C(yellow)%h%C(cyan) %ad%C(red)%d%Creset %s  %C(green)%an%Creset' --abbrev-commit --branches --remotes --tags"
git config --global alias.lsaa "log --graph --date=short --pretty=format:'%C(yellow)%h%C(cyan) %ad%C(red)%d%Creset %s  %C(green)%an%Creset' --abbrev-commit --all --remotes --tags"
git config --global alias.lda "log --graph --date=short --pretty=format:'%C(yellow)%h%C(cyan) %ad%C(red)%d%Creset %s  %C(green)%an%Creset' --abbrev-commit --stat --summary --all"
git config --global alias.pick "cherry-pick"
git config --global alias.p "cherry-pick"
git config --global alias.pa "cherry-pick --abort"
git config --global alias.pc "cherry-pick --continue"
git config --global alias.r "rebase"
git config --global alias.ri "rebase -i"
git config --global alias.ra "rebase --abort"
git config --global alias.rc "rebase --continue"
git config --global alias.s "status --short --branch --untracked-files=all"
